import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database with 20 events...");

  // Use dates relative to now so events always fall within the default 30-day window
  const daysAgo = (d: number) => new Date(Date.now() - d * 86400000);

  const seedEvents = [
    // EARTHQUAKES (USGS)
    {
      externalId: "us7000m1ab",
      source: "USGS" as const,
      type: "EARTHQUAKE" as const,
      title: "M 6.2 - 45 km SE of Hualien, Taiwan",
      description: "45 km southeast of Hualien City, Taiwan. Depth: 15.2 km",
      severity: "HIGH" as const,
      status: "ACTIVE" as const,
      lat: 23.7,
      lon: 121.7,
      country: "Taiwan",
      region: "Hualien County",
      startedAt: daysAgo(9),
    },
    {
      externalId: "us7000m2cd",
      source: "USGS" as const,
      type: "EARTHQUAKE" as const,
      title: "M 4.8 - 12 km N of Ridgecrest, California",
      description: "12 km north of Ridgecrest, California. Depth: 8.1 km",
      severity: "MODERATE" as const,
      status: "ACTIVE" as const,
      lat: 35.7,
      lon: -117.6,
      country: "United States",
      region: "California",
      startedAt: daysAgo(11),
    },
    {
      externalId: "us7000m3ef",
      source: "USGS" as const,
      type: "EARTHQUAKE" as const,
      title: "M 7.1 - 80 km SW of Palu, Indonesia",
      description: "80 km southwest of Palu, Central Sulawesi, Indonesia. Depth: 10 km",
      severity: "EXTREME" as const,
      status: "ACTIVE" as const,
      lat: -1.2,
      lon: 119.5,
      country: "Indonesia",
      region: "Central Sulawesi",
      startedAt: daysAgo(20),
    },
    {
      externalId: "us7000m4gh",
      source: "USGS" as const,
      type: "EARTHQUAKE" as const,
      title: "M 2.1 - 5 km W of The Geysers, California",
      description: "5 km west of The Geysers, California. Depth: 2.3 km",
      severity: "LOW" as const,
      status: "ACTIVE" as const,
      lat: 38.8,
      lon: -122.8,
      country: "United States",
      region: "California",
      startedAt: daysAgo(8),
    },
    // WILDFIRES
    {
      externalId: "EONET_2024_WF001",
      source: "EONET" as const,
      type: "WILDFIRE" as const,
      title: "Thomas Fire Complex, Southern California",
      description: "Large wildfire complex burning in Ventura and Santa Barbara counties",
      severity: "EXTREME" as const,
      status: "ACTIVE" as const,
      lat: 34.4,
      lon: -119.1,
      country: "United States",
      region: "Southern California",
      startedAt: daysAgo(27),
    },
    {
      externalId: "FIRMS_CLU_-22.5_148.3_20240401",
      source: "FIRMS" as const,
      type: "WILDFIRE" as const,
      title: "Active Fire — Queensland, Australia",
      description: "Satellite: VIIRS, Confidence: 85%",
      severity: "HIGH" as const,
      status: "ACTIVE" as const,
      lat: -22.5,
      lon: 148.3,
      country: "Australia",
      region: "Queensland",
      startedAt: daysAgo(16),
    },
    // FLOODS
    {
      externalId: "GDACS_FL_2024_001",
      source: "GDACS" as const,
      type: "FLOOD" as const,
      title: "Severe Flooding in Bangladesh — Sylhet Division",
      description: "Monsoon flooding affecting over 2 million people across Sylhet division",
      severity: "EXTREME" as const,
      status: "ACTIVE" as const,
      lat: 24.9,
      lon: 91.8,
      country: "Bangladesh",
      region: "Sylhet Division",
      startedAt: daysAgo(22),
    },
    {
      externalId: "EONET_2024_FL002",
      source: "EONET" as const,
      type: "FLOOD" as const,
      title: "Rio Grande do Sul Flooding, Brazil",
      description: "Major flooding in southern Brazil affecting Porto Alegre metropolitan area",
      severity: "HIGH" as const,
      status: "ACTIVE" as const,
      lat: -30.0,
      lon: -51.2,
      country: "Brazil",
      region: "Rio Grande do Sul",
      startedAt: daysAgo(22),
    },
    // STORMS
    {
      externalId: "urn:oid:2.49.0.1.840.0.2024.001",
      source: "NOAA" as const,
      type: "STORM" as const,
      title: "Severe Thunderstorm Warning — Dallas-Fort Worth, TX",
      description: "Severe thunderstorm with 70mph winds and quarter-sized hail",
      severity: "HIGH" as const,
      status: "ACTIVE" as const,
      lat: 32.8,
      lon: -96.8,
      country: "United States",
      region: "North Texas",
      startedAt: daysAgo(10),
    },
    {
      externalId: "GDACS_TC_2024_003",
      source: "GDACS" as const,
      type: "STORM" as const,
      title: "Tropical Cyclone Freddy — Mozambique Channel",
      description: "Category 3 tropical cyclone tracking toward Mozambique coast",
      severity: "EXTREME" as const,
      status: "ACTIVE" as const,
      lat: -18.5,
      lon: 38.0,
      country: "Mozambique",
      region: "Zambezia Province",
      startedAt: daysAgo(25),
    },
    {
      externalId: "urn:oid:2.49.0.1.840.0.2024.002",
      source: "NOAA" as const,
      type: "STORM" as const,
      title: "Winter Storm Warning — Denver Metropolitan Area",
      description: "Heavy snow expected, 12-18 inches, with 40mph wind gusts",
      severity: "MODERATE" as const,
      status: "ACTIVE" as const,
      lat: 39.7,
      lon: -104.9,
      country: "United States",
      region: "Colorado Front Range",
      startedAt: daysAgo(12),
    },
    // VOLCANOES
    {
      externalId: "EONET_2024_VO001",
      source: "EONET" as const,
      type: "VOLCANO" as const,
      title: "Kilauea Eruption — Hawaii Volcanoes National Park",
      description: "Ongoing eruption at Kilauea summit caldera, lava fountains reaching 50m",
      severity: "MODERATE" as const,
      status: "ACTIVE" as const,
      lat: 19.4,
      lon: -155.3,
      country: "United States",
      region: "Hawaii",
      startedAt: daysAgo(14),
    },
    {
      externalId: "GDACS_VO_2024_002",
      source: "GDACS" as const,
      type: "VOLCANO" as const,
      title: "Mount Etna Eruption — Sicily, Italy",
      description: "Strombolian activity with ash emissions reaching 5000m altitude",
      severity: "HIGH" as const,
      status: "ACTIVE" as const,
      lat: 37.75,
      lon: 15.0,
      country: "Italy",
      region: "Sicily",
      startedAt: daysAgo(15),
    },
    // DROUGHT
    {
      externalId: "RW_2024_DR001",
      source: "RELIEFWEB" as const,
      type: "DROUGHT" as const,
      title: "Severe Drought — Horn of Africa",
      description: "Fifth consecutive failed rainy season affecting Somalia, Ethiopia, and Kenya",
      severity: "EXTREME" as const,
      status: "ACTIVE" as const,
      lat: 2.0,
      lon: 45.3,
      country: "Somalia",
      region: "Horn of Africa",
      startedAt: daysAgo(5),
    },
    {
      externalId: "RW_2024_DR002",
      source: "RELIEFWEB" as const,
      type: "DROUGHT" as const,
      title: "Agricultural Drought — Maharashtra, India",
      description: "Prolonged dry spell affecting Marathwada region crop yields",
      severity: "HIGH" as const,
      status: "ACTIVE" as const,
      lat: 19.6,
      lon: 75.5,
      country: "India",
      region: "Maharashtra",
      startedAt: daysAgo(7),
    },
    // MIXED
    {
      externalId: "FEMA_4800",
      source: "FEMA" as const,
      type: "STORM" as const,
      title: "FEMA-4800-DR — Louisiana Hurricane Declaration",
      description: "Major disaster declaration for hurricane damage in Louisiana parishes",
      severity: "HIGH" as const,
      status: "ACTIVE" as const,
      lat: 30.5,
      lon: -91.1,
      country: "United States",
      region: "Louisiana",
      startedAt: daysAgo(29),
    },
    {
      externalId: "FEMA_4801",
      source: "FEMA" as const,
      type: "FLOOD" as const,
      title: "FEMA-4801-DR — Kentucky Flooding Declaration",
      description: "Emergency declaration for severe flooding in eastern Kentucky",
      severity: "MODERATE" as const,
      status: "ACTIVE" as const,
      lat: 37.8,
      lon: -83.7,
      country: "United States",
      region: "Kentucky",
      startedAt: daysAgo(17),
    },
    {
      externalId: "GDACS_EQ_2024_010",
      source: "GDACS" as const,
      type: "EARTHQUAKE" as const,
      title: "Earthquake — Central Turkey, Malatya Province",
      description: "Moderate earthquake near populated area, aftershock sequence ongoing",
      severity: "MODERATE" as const,
      status: "ACTIVE" as const,
      lat: 38.4,
      lon: 38.3,
      country: "Turkey",
      region: "Malatya Province",
      startedAt: daysAgo(13),
    },
    {
      externalId: "NOAA_2024_WF_003",
      source: "NOAA" as const,
      type: "WILDFIRE" as const,
      title: "Red Flag Warning — Central Oregon",
      description: "Critical fire weather conditions with gusty winds and low humidity",
      severity: "MODERATE" as const,
      status: "ACTIVE" as const,
      lat: 44.0,
      lon: -121.2,
      country: "United States",
      region: "Central Oregon",
      startedAt: daysAgo(8),
    },
    {
      externalId: "EONET_2024_OT001",
      source: "EONET" as const,
      type: "OTHER" as const,
      title: "Dust Storm — Saharan Africa",
      description: "Large-scale dust and sand storm event visible from satellite",
      severity: "LOW" as const,
      status: "ACTIVE" as const,
      lat: 18.5,
      lon: 12.0,
      country: "Chad",
      region: "Sahel",
      startedAt: daysAgo(14),
    },
  ];

  // Upsert all seed events
  for (const event of seedEvents) {
    await prisma.event.upsert({
      where: {
        source_external_id: {
          source: event.source,
          externalId: event.externalId,
        },
      },
      update: {
        title: event.title,
        description: event.description,
        severity: event.severity,
        status: event.status,
      },
      create: {
        externalId: event.externalId,
        source: event.source,
        type: event.type,
        title: event.title,
        description: event.description ?? null,
        severity: event.severity ?? null,
        status: event.status,
        lat: event.lat,
        lon: event.lon,
        country: event.country ?? null,
        region: event.region ?? null,
        startedAt: event.startedAt,
        rawData: { seeded: true },
      },
    });
  }

  // Seed source status entries
  const sources = ["USGS", "EONET", "GDACS", "FEMA", "RELIEFWEB", "FIRMS", "NOAA"] as const;
  for (const source of sources) {
    await prisma.sourceStatus.upsert({
      where: { source },
      update: {},
      create: {
        source,
        lastFetchedAt: null,
        eventCount: 0,
        isHealthy: true,
      },
    });
  }

  const count = await prisma.event.count();
  console.log(`Seed complete. ${count} events in database.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
